import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import AuthProvider from "@/components/AuthProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Image World",
  description: "It is a fun platform, where users can share and checkout images generated by other users and can share there own work via AI-based generation or Self hosted.",
  icons: {
    icon: [
      {
        url: '/logo.ico',
        sizes: 'any',
      }
    ]}
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navbar />
          <main className="pt-10">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
